import { useState } from 'react';
import { VaccinationRecord, UserProfile, CountryPeriod } from '@/types';
import { Share2, Download, Link as LinkIcon, Mail, Copy, CheckCircle, CreditCard, Shield } from 'lucide-react';
import { CustomSelect } from '@/components/CustomSelect';
import jsPDF from 'jspdf';
import { useI18n } from '@/lib/i18n';

interface ShareRecordsProps {
  vaccinations: VaccinationRecord[];
  profile: UserProfile | null;
  countryHistory: CountryPeriod[];
  userEmail?: string;
}

function parseLocalDate(dateStr: string): Date {
  const [year, month, day] = dateStr.split('-').map(Number);
  return new Date(year, month - 1, day);
}

function formatDate(dateStr: string | undefined | null, options?: Intl.DateTimeFormatOptions): string {
  if (!dateStr) return 'N/A';
  const parts = dateStr.split('-');
  if (parts.length !== 3) return dateStr;
  const [year, month, day] = parts.map(Number);
  if (!year || !month || !day) return dateStr;
  return new Date(year, month - 1, day).toLocaleDateString('en-US', options);
}

export function ShareRecords({ vaccinations, profile, countryHistory, userEmail }: ShareRecordsProps) {
  const { t } = useI18n();
  const [shareMethod, setShareMethod] = useState<'link' | 'email' | 'pdf' | 'card' | null>(null);
  const [email, setEmail] = useState('');
  const [message, setMessage] = useState('');
  const [expirationDays, setExpirationDays] = useState(7);
  const [allowDownload, setAllowDownload] = useState(true);
  const [copied, setCopied] = useState(false);
  const [emailSent, setEmailSent] = useState(false);

  const mockShareLink = 'https://dozeyrecords.com/share/abc123xyz';

  const handleCopyLink = () => {
    navigator.clipboard.writeText(mockShareLink);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const BRAND = {
    blue: [74, 127, 181] as [number, number, number],
    green: [138, 171, 69] as [number, number, number],
    darkGreen: [77, 144, 104] as [number, number, number],
    black: [29, 29, 31] as [number, number, number],
    gray: [134, 134, 139] as [number, number, number],
    lightGray: [245, 245, 247] as [number, number, number],
    white: [251, 251, 253] as [number, number, number],
  };

  const drawPdfHeader = (doc: jsPDF, pageW: number) => {
    doc.setFillColor(...BRAND.blue);
    doc.rect(0, 0, pageW, 38, 'F');
    const gradientSteps = 10;
    for (let i = 0; i < gradientSteps; i++) {
      const ratio = i / gradientSteps;
      const r = Math.round(BRAND.blue[0] + (BRAND.darkGreen[0] - BRAND.blue[0]) * ratio);
      const g = Math.round(BRAND.blue[1] + (BRAND.darkGreen[1] - BRAND.blue[1]) * ratio);
      const b = Math.round(BRAND.blue[2] + (BRAND.darkGreen[2] - BRAND.blue[2]) * ratio);
      doc.setFillColor(r, g, b);
      doc.rect((pageW / gradientSteps) * i, 0, pageW / gradientSteps + 1, 38, 'F');
    }
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    doc.text('DOZEY', 20, 18);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.text('VACCINATION RECORDS', 20, 28);
    doc.text('dozeyrecords.com', pageW - 20, 28, { align: 'right' });
  };

  const drawPdfFooter = (doc: jsPDF, pageW: number, pageH: number, pageNum: number, totalPages: number) => {
    doc.setDrawColor(...BRAND.lightGray);
    doc.line(20, pageH - 18, pageW - 20, pageH - 18);
    doc.setFontSize(7);
    doc.setTextColor(...BRAND.gray);
    doc.setFont('helvetica', 'normal');
    doc.text(`Generated by DOZEY on ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`, 20, pageH - 12);
    doc.text(`Page ${pageNum} of ${totalPages}`, pageW - 20, pageH - 12, { align: 'right' });
    doc.setFontSize(6);
    doc.text('This document is for informational purposes. Verify records with your healthcare provider.', 20, pageH - 7);
  };

  const generateVaccineCard = () => {
    const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
    const pageW = doc.internal.pageSize.getWidth();
    const pageH = doc.internal.pageSize.getHeight();

    drawPdfHeader(doc, pageW);

    doc.setTextColor(...BRAND.black);
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text('Vaccination Record Card', pageW / 2, 54, { align: 'center' });

    doc.setFillColor(...BRAND.lightGray);
    doc.roundedRect(20, 62, pageW - 40, profile ? 36 : 16, 3, 3, 'F');

    let yPos = 72;
    if (profile) {
      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(...BRAND.gray);
      doc.text('Name', 28, yPos);
      doc.text('Date of Birth', pageW / 2, yPos);
      yPos += 6;
      doc.setFontSize(11);
      doc.setTextColor(...BRAND.black);
      doc.setFont('helvetica', 'bold');
      doc.text(profile.fullName || 'N/A', 28, yPos);
      doc.text(formatDate(profile.dateOfBirth), pageW / 2, yPos);
      yPos += 8;
      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(...BRAND.gray);
      doc.text('Country of Origin', 28, yPos);
      doc.text('Healthcare Provider', pageW / 2, yPos);
      yPos += 6;
      doc.setFontSize(10);
      doc.setTextColor(...BRAND.black);
      doc.setFont('helvetica', 'normal');
      doc.text(profile.countryOfOrigin || 'N/A', 28, yPos);
      doc.text(profile.primaryProvider || 'N/A', pageW / 2, yPos);
      yPos += 12;
    } else {
      yPos = 82;
    }

    const groupedByVaccine: Record<string, VaccinationRecord[]> = {};
    vaccinations.forEach(v => {
      if (!groupedByVaccine[v.vaccineName]) groupedByVaccine[v.vaccineName] = [];
      groupedByVaccine[v.vaccineName].push(v);
    });
    Object.values(groupedByVaccine).forEach(group => {
      group.sort((a, b) => new Date(a.date).getTime() - new Date(b.date).getTime());
    });

    const colX = [28, 50, 90, 132];
    const colW = [22, 40, 42, pageW - 40 - 132 + 20];

    yPos += 4;
    doc.setFillColor(...BRAND.blue);
    doc.roundedRect(20, yPos - 5, pageW - 40, 8, 2, 2, 'F');
    doc.setFontSize(8);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(255, 255, 255);
    doc.text('DOSE', colX[0], yPos);
    doc.text('DATE', colX[1], yPos);
    doc.text('PROVIDER', colX[2], yPos);
    doc.text('LOCATION / COUNTRY', colX[3], yPos);
    yPos += 6;

    let pageNum = 1;
    const checkPageBreak = (needed: number) => {
      if (yPos + needed > pageH - 25) {
        drawPdfFooter(doc, pageW, pageH, pageNum, 0);
        doc.addPage();
        pageNum++;
        drawPdfHeader(doc, pageW);
        yPos = 48;
        return true;
      }
      return false;
    };

    Object.entries(groupedByVaccine).forEach(([vaccine, doses]) => {
      checkPageBreak(14 + doses.length * 7);

      doc.setFillColor(...BRAND.lightGray);
      doc.roundedRect(20, yPos - 4, pageW - 40, 8, 1, 1, 'F');
      doc.setFontSize(10);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...BRAND.black);
      doc.text(vaccine, 28, yPos + 1);

      const verified = doses.every(d => d.verified);
      if (verified) {
        doc.setFontSize(7);
        doc.setTextColor(...BRAND.darkGreen);
        doc.text('VERIFIED', pageW - 28, yPos + 1, { align: 'right' });
      }
      yPos += 8;

      doses.forEach((dose, i) => {
        checkPageBreak(8);
        if (i % 2 === 0) {
          doc.setFillColor(250, 250, 252);
          doc.rect(20, yPos - 4, pageW - 40, 7, 'F');
        }
        doc.setFontSize(8);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(...BRAND.black);
        doc.text(`Dose ${dose.doseNumber || '—'}`, colX[0], yPos);
        doc.text(formatDate(dose.date, { year: 'numeric', month: 'short', day: 'numeric' }), colX[1], yPos);
        doc.setTextColor(...BRAND.gray);
        doc.text((dose.provider || 'N/A').substring(0, 24), colX[2], yPos);
        doc.text((dose.location || dose.countryGiven || 'N/A').substring(0, 22), colX[3], yPos);
        yPos += 7;
      });
      yPos += 3;
    });

    yPos += 6;
    checkPageBreak(20);
    doc.setDrawColor(...BRAND.lightGray);
    doc.line(20, yPos, pageW - 20, yPos);
    yPos += 8;

    doc.setFontSize(9);
    doc.setTextColor(...BRAND.gray);
    doc.setFont('helvetica', 'normal');
    doc.text(`Total Vaccinations: ${vaccinations.length}`, 28, yPos);
    doc.text(`Verified: ${vaccinations.filter(v => v.verified).length}`, pageW / 2, yPos);
    yPos += 6;
    doc.text(`Generated: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`, 28, yPos);

    for (let p = 1; p <= pageNum; p++) {
      doc.setPage(p);
      drawPdfFooter(doc, pageW, pageH, p, pageNum);
    }

    doc.save(`dozey-vaccine-card-${profile?.fullName?.replace(/\s+/g, '-').toLowerCase() || 'record'}.pdf`);
  };

  const generatePDF = () => {
    const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
    const pageW = doc.internal.pageSize.getWidth();
    const pageH = doc.internal.pageSize.getHeight();
    let pageNum = 1;

    drawPdfHeader(doc, pageW);

    let yPos = 50;

    const checkPageBreak = (needed: number) => {
      if (yPos + needed > pageH - 25) {
        drawPdfFooter(doc, pageW, pageH, pageNum, 0);
        doc.addPage();
        pageNum++;
        drawPdfHeader(doc, pageW);
        yPos = 48;
        return true;
      }
      return false;
    };

    doc.setTextColor(...BRAND.black);
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.text('Vaccination Records Summary', pageW / 2, yPos, { align: 'center' });
    yPos += 12;

    if (profile) {
      doc.setFontSize(11);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...BRAND.blue);
      doc.text('PATIENT INFORMATION', 20, yPos);
      yPos += 2;
      doc.setDrawColor(...BRAND.blue);
      doc.setLineWidth(0.5);
      doc.line(20, yPos, pageW - 20, yPos);
      yPos += 8;

      doc.setFillColor(...BRAND.lightGray);
      doc.roundedRect(20, yPos - 5, pageW - 40, 42, 3, 3, 'F');

      const infoFields = [
        ['Name', profile.fullName || 'N/A'],
        ['Date of Birth', formatDate(profile.dateOfBirth)],
        ['Country of Origin', profile.countryOfOrigin || 'N/A'],
        ['Current Location', [profile.currentState, profile.currentCountry].filter(Boolean).join(', ') || 'N/A'],
        ['Citizenships', profile.citizenships?.length ? profile.citizenships.join(', ') : 'N/A'],
        ['Healthcare Provider', profile.primaryProvider || 'N/A'],
      ];

      infoFields.forEach(([label, value]) => {
        doc.setFontSize(8);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(...BRAND.gray);
        doc.text(label, 28, yPos);
        doc.setFontSize(10);
        doc.setTextColor(...BRAND.black);
        doc.setFont('helvetica', 'normal');
        doc.text(String(value), 75, yPos);
        yPos += 6;
      });
      yPos += 6;
    }

    if (countryHistory.length > 0) {
      checkPageBreak(20 + countryHistory.length * 8);
      doc.setFontSize(11);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...BRAND.blue);
      doc.text('RESIDENCE HISTORY', 20, yPos);
      yPos += 2;
      doc.setDrawColor(...BRAND.blue);
      doc.setLineWidth(0.5);
      doc.line(20, yPos, pageW - 20, yPos);
      yPos += 8;

      const sorted = [...countryHistory].sort((a, b) => a.startYear - b.startYear);
      sorted.forEach((period, i) => {
        checkPageBreak(10);
        if (i % 2 === 0) {
          doc.setFillColor(250, 250, 252);
          doc.rect(20, yPos - 4, pageW - 40, 8, 'F');
        }
        doc.setFontSize(9);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(...BRAND.black);
        doc.text(`${period.country}${period.state ? `, ${period.state}` : ''}`, 28, yPos);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(...BRAND.gray);
        doc.text(`${period.startYear} - ${period.endYear || 'Present'}`, pageW - 28, yPos, { align: 'right' });
        yPos += 8;
      });
      yPos += 6;
    }

    checkPageBreak(20);
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...BRAND.blue);
    doc.text('VACCINATION RECORDS', 20, yPos);
    yPos += 2;
    doc.setDrawColor(...BRAND.blue);
    doc.setLineWidth(0.5);
    doc.line(20, yPos, pageW - 20, yPos);
    yPos += 8;

    const statBoxW = (pageW - 40 - 8) / 3;
    [
      [`${vaccinations.length}`, 'Total Vaccinations'],
      [`${vaccinations.filter(v => v.verified).length}`, 'Verified'],
      [`${vaccinations.filter(v => !v.verified).length}`, 'Pending'],
    ].forEach(([num, label], i) => {
      const xStart = 20 + i * (statBoxW + 4);
      doc.setFillColor(...BRAND.lightGray);
      doc.roundedRect(xStart, yPos - 4, statBoxW, 16, 2, 2, 'F');
      doc.setFontSize(14);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...BRAND.black);
      doc.text(num, xStart + statBoxW / 2, yPos + 3, { align: 'center' });
      doc.setFontSize(7);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(...BRAND.gray);
      doc.text(label, xStart + statBoxW / 2, yPos + 9, { align: 'center' });
    });
    yPos += 20;

    const sortedVaccinations = [...vaccinations].sort(
      (a, b) => parseLocalDate(b.date).getTime() - parseLocalDate(a.date).getTime()
    );

    sortedVaccinations.forEach((vax, index) => {
      checkPageBreak(24);

      doc.setFillColor(index % 2 === 0 ? 250 : 245, index % 2 === 0 ? 250 : 245, index % 2 === 0 ? 252 : 247);
      doc.roundedRect(20, yPos - 4, pageW - 40, 20, 2, 2, 'F');

      doc.setFontSize(10);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...BRAND.black);
      doc.text(`${index + 1}. ${vax.vaccineName}`, 28, yPos + 1);

      doc.setFontSize(8);
      doc.setFont('helvetica', 'normal');
      if (vax.verified) {
        doc.setTextColor(...BRAND.darkGreen);
        doc.text('Verified', pageW - 28, yPos + 1, { align: 'right' });
      } else {
        doc.setTextColor(180, 130, 50);
        doc.text('Pending', pageW - 28, yPos + 1, { align: 'right' });
      }

      yPos += 6;
      doc.setFontSize(8);
      doc.setTextColor(...BRAND.gray);
      doc.setFont('helvetica', 'normal');
      const details = [
        `Dose ${vax.doseNumber || '—'}`,
        formatDate(vax.date, { year: 'numeric', month: 'short', day: 'numeric' }),
        vax.countryGiven || '',
        vax.provider || '',
      ].filter(Boolean);
      doc.text(details.join('  |  '), 28, yPos + 1);

      if (vax.location) {
        yPos += 5;
        doc.text(`Location: ${vax.location}`, 28, yPos + 1);
      }
      if (vax.notes) {
        yPos += 5;
        const notesText = doc.splitTextToSize(`Notes: ${vax.notes}`, pageW - 60);
        doc.text(notesText[0], 28, yPos + 1);
      }

      yPos += 8;
    });

    for (let p = 1; p <= pageNum; p++) {
      doc.setPage(p);
      drawPdfFooter(doc, pageW, pageH, p, pageNum);
    }

    doc.save(`dozey-vaccination-summary-${profile?.fullName?.replace(/\s+/g, '-').toLowerCase() || 'records'}.pdf`);
  };

  const buildEmailBody = () => {
    let body = '';
    if (message) body += message + '\n\n---\n\n';
    body += 'VACCINATION RECORDS SUMMARY\n';
    body += `Shared by: ${profile?.fullName || 'DOZEY User'}`;
    if (userEmail) body += ` (${userEmail})`;
    body += '\n\n';
    if (profile) {
      body += `Name: ${profile.fullName}\n`;
      body += `Date of Birth: ${formatDate(profile.dateOfBirth)}\n`;
      body += `Country of Origin: ${profile.countryOfOrigin}\n\n`;
    }
    body += `Total Vaccinations: ${vaccinations.length}\n`;
    body += `Verified: ${vaccinations.filter(v => v.verified).length}\n\n`;
    const sorted = [...vaccinations].sort(
      (a, b) => parseLocalDate(b.date).getTime() - parseLocalDate(a.date).getTime()
    );
    sorted.forEach((vax, i) => {
      body += `${i + 1}. ${vax.vaccineName} - Dose ${vax.doseNumber}\n`;
      body += `   Date: ${formatDate(vax.date)}\n`;
      body += `   Country: ${vax.countryGiven || 'N/A'}\n`;
      body += `   Status: ${vax.verified ? 'Verified' : 'Pending'}\n`;
      if (vax.provider) body += `   Provider: ${vax.provider}\n`;
      body += '\n';
    });
    body += '---\nGenerated by DOZEY - dozeyrecords.com\n';
    return body;
  };

  const handleSendEmail = () => {
    const subject = `Vaccination Records - ${profile?.fullName || 'DOZEY User'}`;
    const body = buildEmailBody();
    const mailtoUrl = `mailto:${encodeURIComponent(email)}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
    window.open(mailtoUrl, '_blank');
    setEmailSent(true);
    setTimeout(() => setEmailSent(false), 5000);
  };

  return (
    <div>
      <div className="bg-white rounded-2xl border-0 p-8">
        <div className="flex items-center gap-3 mb-6">
          <Share2 className="w-8 h-8 text-[#1d1d1f]/30" />
          <div>
            <h1 className="text-[#1d1d1f] font-semibold">{t('shareYourRecords')}</h1>
            <p className="text-[#86868b]">{t('shareDescription')}</p>
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-4 gap-4 mb-8">
          <button
            onClick={() => setShareMethod('card')}
            className={`p-6 rounded-2xl border transition-all ${
              shareMethod === 'card'
                ? 'border-[#4a7fb5] bg-[#4a7fb5]/5'
                : 'border-black/5 hover:border-[#4a7fb5]/50'
            }`}
          >
            <CreditCard className={`w-8 h-8 mx-auto mb-3 ${shareMethod === 'card' ? 'text-[#4a7fb5]' : 'text-[#1d1d1f]/30'}`} />
            <h3 className="text-[#1d1d1f] font-semibold mb-1">{t('vaccineCard')}</h3>
            <p className="text-[#86868b] text-sm">{t('vaccineCardDesc')}</p>
          </button>

          <button
            onClick={() => setShareMethod('link')}
            className={`p-6 rounded-2xl border transition-all ${
              shareMethod === 'link'
                ? 'border-[#4a7fb5] bg-[#4a7fb5]/5'
                : 'border-black/5 hover:border-[#4a7fb5]/50'
            }`}
          >
            <LinkIcon className={`w-8 h-8 mx-auto mb-3 ${shareMethod === 'link' ? 'text-[#4a7fb5]' : 'text-[#1d1d1f]/30'}`} />
            <h3 className="text-[#1d1d1f] font-semibold mb-1">{t('shareLink')}</h3>
            <p className="text-[#86868b] text-sm">{t('shareLinkDesc')}</p>
          </button>

          <button
            onClick={() => setShareMethod('email')}
            className={`p-6 rounded-2xl border transition-all ${
              shareMethod === 'email'
                ? 'border-[#4a7fb5] bg-[#4a7fb5]/5'
                : 'border-black/5 hover:border-[#4a7fb5]/50'
            }`}
          >
            <Mail className={`w-8 h-8 mx-auto mb-3 ${shareMethod === 'email' ? 'text-[#4a7fb5]' : 'text-[#1d1d1f]/30'}`} />
            <h3 className="text-[#1d1d1f] font-semibold mb-1">{t('sendEmail')}</h3>
            <p className="text-[#86868b] text-sm">{t('sendEmailDesc')}</p>
          </button>

          <button
            onClick={() => setShareMethod('pdf')}
            className={`p-6 rounded-2xl border transition-all ${
              shareMethod === 'pdf'
                ? 'border-[#4a7fb5] bg-[#4a7fb5]/5'
                : 'border-black/5 hover:border-[#4a7fb5]/50'
            }`}
          >
            <Download className={`w-8 h-8 mx-auto mb-3 ${shareMethod === 'pdf' ? 'text-[#4a7fb5]' : 'text-[#1d1d1f]/30'}`} />
            <h3 className="text-[#1d1d1f] font-semibold mb-1">{t('fullSummary')}</h3>
            <p className="text-[#86868b] text-sm">{t('fullSummaryDesc')}</p>
          </button>
        </div>

        {shareMethod === 'card' && (
          <div className="bg-[#f5f5f7] p-6 rounded-2xl">
            <h3 className="text-[#1d1d1f] font-semibold mb-4">Vaccine Card Export</h3>
            <p className="text-[#86868b] mb-6 text-sm">
              Download your vaccination records in a compact card format similar to COVID-19 vaccine cards.
              Lists each vaccine with dose numbers, dates, providers, and locations.
            </p>

            <div className="bg-white border-2 border-[#4a7fb5] rounded-xl p-6 mb-6 max-w-md mx-auto shadow-sm">
              <div className="text-center border-b-2 border-[#4a7fb5] pb-3 mb-4">
                <div className="text-[#4a7fb5] font-semibold text-lg">VACCINATION RECORD CARD</div>
                <div className="text-[#8aab45] font-semibold text-sm">DOZEY</div>
              </div>
              <div className="space-y-2 text-sm mb-4">
                <div className="flex">
                  <span className="text-[#86868b] w-28 shrink-0">Name:</span>
                  <span className="text-[#1d1d1f] font-medium">{profile?.fullName || 'Your Name'}</span>
                </div>
                <div className="flex">
                  <span className="text-[#86868b] w-28 shrink-0">Date of Birth:</span>
                  <span className="text-[#1d1d1f] font-medium">{formatDate(profile?.dateOfBirth)}</span>
                </div>
              </div>
              <div className="border-t border-0 pt-3">
                <div className="text-xs text-[#86868b] mb-2 uppercase tracking-wide font-medium">Vaccinations ({vaccinations.length})</div>
                {vaccinations.slice(0, 3).map((v, i) => (
                  <div key={i} className="flex justify-between text-xs py-1 border-b border-black/5">
                    <span className="font-medium text-[#1d1d1f]">{v.vaccineName} (Dose {v.doseNumber})</span>
                    <span className="text-[#86868b]">{formatDate(v.date, { month: 'short', day: 'numeric', year: '2-digit' })}</span>
                  </div>
                ))}
                {vaccinations.length > 3 && (
                  <div className="text-xs text-[#86868b] pt-1">+ {vaccinations.length - 3} more</div>
                )}
              </div>
            </div>

            <button
              onClick={generateVaccineCard}
              className="w-full bg-[#4a7fb5] hover:bg-[#3a6a9a] text-white py-3 rounded-full transition-colors flex items-center justify-center gap-2 font-semibold"
            >
              <CreditCard className="w-5 h-5" />
              {t('downloadVaccineCard')}
            </button>
          </div>
        )}

        {shareMethod === 'link' && (
          <div className="bg-[#f5f5f7] p-6 rounded-2xl">
            <h3 className="text-[#1d1d1f] font-semibold mb-4">{t('generateSecureLink')}</h3>
            
            <div className="space-y-4 mb-6">
              <CustomSelect
                id="expiration"
                label={t('linkExpiration')}
                value={String(expirationDays)}
                onChange={(val) => setExpirationDays(parseInt(val))}
                options={[
                  { value: '1', label: '1 day' },
                  { value: '7', label: '7 days' },
                  { value: '30', label: '30 days' },
                  { value: '90', label: '90 days' },
                ]}
              />

              <div className="flex items-center gap-2">
                <input
                  type="checkbox"
                  id="allowDownload"
                  checked={allowDownload}
                  onChange={(e) => setAllowDownload(e.target.checked)}
                  className="w-4 h-4 text-[#8aab45]"
                />
                <label htmlFor="allowDownload" className="text-[#1d1d1f]">
                  {t('allowDownloads')}
                </label>
              </div>
            </div>

            <div className="bg-white p-4 rounded-2xl border-0 flex items-center gap-3 mb-4">
              <code className="flex-1 text-sm text-[#86868b] break-all">{mockShareLink}</code>
              <button
                onClick={handleCopyLink}
                className="bg-[#8aab45] hover:bg-[#6d8a35] text-white px-4 py-2 rounded-full transition-colors flex items-center gap-2"
              >
                {copied ? (
                  <>
                    <CheckCircle className="w-4 h-4" />
                    {t('linkCopied')}
                  </>
                ) : (
                  <>
                    <Copy className="w-4 h-4" />
                    {t('copyLink')}
                  </>
                )}
              </button>
            </div>

            <p className="text-[#86868b] text-sm">
              This link will expire in {expirationDays} day{expirationDays !== 1 ? 's' : ''} and can be accessed by anyone with the URL.
            </p>
          </div>
        )}

        {shareMethod === 'email' && (
          <div className="bg-[#f5f5f7] p-6 rounded-2xl">
            <h3 className="text-[#1d1d1f] font-semibold mb-4">{t('sendViaEmail')}</h3>

            {userEmail && (
              <div className="bg-white rounded-xl p-3 mb-4 flex items-center gap-2">
                <Mail className="w-4 h-4 text-[#4a7fb5]" />
                <span className="text-sm text-[#86868b]">Sending from:</span>
                <span className="text-sm font-medium text-[#1d1d1f]">{userEmail}</span>
              </div>
            )}
            
            <div className="space-y-4">
              <div>
                <label htmlFor="recipientEmail" className="block text-[#1d1d1f] mb-2">
                  {t('recipientEmail')} *
                </label>
                <input
                  type="email"
                  id="recipientEmail"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  placeholder="doctor@clinic.com"
                  className="w-full px-4 py-2 bg-white border-0 rounded-xl focus:ring-2 focus:ring-[#4a7fb5] focus:border-transparent outline-none"
                />
              </div>

              <div>
                <label htmlFor="emailMessage" className="block text-[#1d1d1f] mb-2">
                  Message (Optional)
                </label>
                <textarea
                  id="emailMessage"
                  value={message}
                  onChange={(e) => setMessage(e.target.value)}
                  rows={4}
                  placeholder="Add a message to your healthcare provider..."
                  className="w-full px-4 py-2 bg-white border-0 rounded-xl focus:ring-2 focus:ring-[#4a7fb5] focus:border-transparent outline-none resize-none"
                />
              </div>

              {emailSent && (
                <div className="bg-[#4d9068]/10 text-[#4d9068] p-3 rounded-xl text-sm flex items-center gap-2">
                  <CheckCircle className="w-4 h-4" />
                  {t('emailSent')}
                </div>
              )}

              <button
                onClick={handleSendEmail}
                disabled={!email}
                className="w-full bg-[#8aab45] hover:bg-[#6d8a35] disabled:bg-[#e8e8ed] disabled:text-[#86868b] disabled:cursor-not-allowed text-white py-3 rounded-full transition-colors flex items-center justify-center gap-2"
              >
                <Mail className="w-5 h-5" />
                Open Email to Send
              </button>

              <p className="text-[#86868b] text-xs">
                This will open your email client with a pre-filled vaccination summary. The email will be sent from your registered account ({userEmail || 'your email'}).
              </p>
            </div>
          </div>
        )}

        {shareMethod === 'pdf' && (
          <div className="bg-[#f5f5f7] p-6 rounded-2xl">
            <h3 className="text-[#1d1d1f] font-semibold mb-4">{t('downloadSummary')}</h3>
            
            <div className="bg-white p-6 rounded-2xl border-0 mb-4">
              <h4 className="text-[#1d1d1f] font-semibold mb-3">{t('whatsIncluded')}</h4>
              <ul className="space-y-2 text-[#86868b]">
                <li className="flex items-center gap-2">
                  <CheckCircle className="w-5 h-5 text-green-500" />
                  {t('completePatientProfile')}
                </li>
                <li className="flex items-center gap-2">
                  <CheckCircle className="w-5 h-5 text-green-500" />
                  {t('fullVaccinationHistory')} ({vaccinations.length} records)
                </li>
                <li className="flex items-center gap-2">
                  <CheckCircle className="w-5 h-5 text-green-500" />
                  {t('countryResidenceTimeline')}
                </li>
                <li className="flex items-center gap-2">
                  <CheckCircle className="w-5 h-5 text-green-500" />
                  {t('verificationStatus')}
                </li>
              </ul>
            </div>

            <button
              onClick={generatePDF}
              className="w-full bg-[#8aab45] hover:bg-[#6d8a35] text-white py-3 rounded-full transition-colors flex items-center justify-center gap-2"
            >
              <Download className="w-5 h-5" />
              {t('downloadSummary')}
            </button>
          </div>
        )}

        <div className="mt-8 bg-[#f5f5f7] rounded-2xl border-0 p-5">
          <div className="flex items-center gap-2 mb-2">
            <Shield className="w-5 h-5 text-[#1d1d1f]/30" />
            <h4 className="text-[#1d1d1f] font-semibold">{t('securityNotice')}</h4>
          </div>
          <p className="text-[#86868b] text-sm">
            {t('hipaaNotice')}
          </p>
        </div>
      </div>
    </div>
  );
}
