import { useState } from 'react';
import { VaccinationRecord, UserProfile, CountryPeriod } from '@/types';
import { Share2, Download, Link as LinkIcon, Mail, Copy, CheckCircle, CreditCard, Shield } from 'lucide-react';
import { CustomSelect } from '@/components/CustomSelect';

interface ShareRecordsProps {
  vaccinations: VaccinationRecord[];
  profile: UserProfile | null;
  countryHistory: CountryPeriod[];
}

function parseLocalDate(dateStr: string): Date {
  const [year, month, day] = dateStr.split('-').map(Number);
  return new Date(year, month - 1, day);
}

function formatDate(dateStr: string | undefined | null, options?: Intl.DateTimeFormatOptions): string {
  if (!dateStr) return 'N/A';
  const parts = dateStr.split('-');
  if (parts.length !== 3) return dateStr;
  const [year, month, day] = parts.map(Number);
  if (!year || !month || !day) return dateStr;
  return new Date(year, month - 1, day).toLocaleDateString('en-US', options);
}

export function ShareRecords({ vaccinations, profile, countryHistory }: ShareRecordsProps) {
  const [shareMethod, setShareMethod] = useState<'link' | 'email' | 'pdf' | 'card' | null>(null);
  const [email, setEmail] = useState('');
  const [message, setMessage] = useState('');
  const [expirationDays, setExpirationDays] = useState(7);
  const [allowDownload, setAllowDownload] = useState(true);
  const [copied, setCopied] = useState(false);

  const mockShareLink = 'https://dozeyrecords.com/share/abc123xyz';

  const handleCopyLink = () => {
    navigator.clipboard.writeText(mockShareLink);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const generateVaccineCard = () => {
    const groupedByVaccine: Record<string, VaccinationRecord[]> = {};
    vaccinations.forEach(v => {
      if (!groupedByVaccine[v.vaccineName]) {
        groupedByVaccine[v.vaccineName] = [];
      }
      groupedByVaccine[v.vaccineName].push(v);
    });

    Object.values(groupedByVaccine).forEach(group => {
      group.sort((a, b) => new Date(a.date).getTime() - new Date(b.date).getTime());
    });

    let card = '';
    card += '╔══════════════════════════════════════════════════════════╗\n';
    card += '║              VACCINATION RECORD CARD                    ║\n';
    card += '║                      DOZEY                              ║\n';
    card += '╠══════════════════════════════════════════════════════════╣\n';
    card += '║                                                         ║\n';

    if (profile) {
      card += `║  Name: ${(profile.fullName || '').padEnd(48)}║\n`;
      card += `║  Date of Birth: ${formatDate(profile.dateOfBirth).padEnd(39)}║\n`;
      card += `║  Country of Origin: ${(profile.countryOfOrigin || 'N/A').padEnd(36)}║\n`;
      if (profile.primaryProvider) {
        card += `║  Primary Provider: ${(profile.primaryProvider).padEnd(37)}║\n`;
      }
    }

    card += '║                                                         ║\n';
    card += '╠══════════════════════════════════════════════════════════╣\n';

    Object.entries(groupedByVaccine).forEach(([vaccine, doses]) => {
      card += '║                                                         ║\n';
      card += `║  ${vaccine.padEnd(55)}║\n`;
      card += '║  ─────────────────────────────────────────────────────  ║\n';
      card += '║  Dose  │  Date          │  Provider         │  Location║\n';
      card += '║  ──────┼────────────────┼───────────────────┼─────────║\n';

      doses.forEach(dose => {
        const doseNum = `  ${dose.doseNumber}`.padEnd(6);
        const date = `  ${formatDate(dose.date, { year: 'numeric', month: '2-digit', day: '2-digit' })}`.padEnd(16);
        const prov = `  ${(dose.provider || 'N/A').substring(0, 17)}`.padEnd(19);
        const loc = `  ${(dose.location || dose.countryGiven || 'N/A').substring(0, 8)}`;
        card += `║  ${doseNum}│${date}│${prov}│${loc}║\n`;
      });
    });

    card += '║                                                         ║\n';
    card += '╠══════════════════════════════════════════════════════════╣\n';
    card += `║  Total Vaccines: ${String(vaccinations.length).padEnd(39)}║\n`;
    card += `║  Verified: ${String(vaccinations.filter(v => v.verified).length).padEnd(45)}║\n`;
    card += `║  Generated: ${new Date().toLocaleDateString().padEnd(44)}║\n`;
    card += '║                                                         ║\n';
    card += '║  This record was generated by DOZEY                     ║\n';
    card += '║  dozeyrecords.com                                       ║\n';
    card += '╚══════════════════════════════════════════════════════════╝\n';

    const blob = new Blob([card], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `dozey-vaccine-card-${profile?.fullName?.replace(/\s+/g, '-').toLowerCase() || 'record'}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const generatePDF = () => {
    let summary = '═══════════════════════════════════════\n';
    summary += '   VACCINATION RECORDS SUMMARY\n';
    summary += '═══════════════════════════════════════\n\n';

    if (profile) {
      summary += 'PATIENT INFORMATION\n';
      summary += '───────────────────────────────────────\n';
      summary += `Name: ${profile.fullName}\n`;
      summary += `Date of Birth: ${formatDate(profile.dateOfBirth)}\n`;
      summary += `Country of Origin: ${profile.countryOfOrigin}\n`;
      summary += `Current Location: ${profile.currentState}, ${profile.currentCountry}\n`;
      if (profile.citizenships.length > 0) {
        summary += `Citizenships: ${profile.citizenships.join(', ')}\n`;
      }
      if (profile.languages.length > 0) {
        summary += `Languages: ${profile.languages.join(', ')}\n`;
      }
      if (profile.primaryProvider) {
        summary += `Primary Provider: ${profile.primaryProvider}\n`;
      }
      summary += '\n';
    }

    if (countryHistory.length > 0) {
      summary += 'RESIDENCE HISTORY\n';
      summary += '───────────────────────────────────────\n';
      countryHistory
        .sort((a, b) => a.startYear - b.startYear)
        .forEach(period => {
          summary += `• ${period.country}${period.state ? `, ${period.state}` : ''}\n`;
          summary += `  ${period.startYear} - ${period.endYear}\n`;
        });
      summary += '\n';
    }

    summary += 'VACCINATION RECORDS\n';
    summary += '───────────────────────────────────────\n';
    summary += `Total Vaccines: ${vaccinations.length}\n`;
    summary += `Verified: ${vaccinations.filter(v => v.verified).length}\n`;
    summary += `Pending Verification: ${vaccinations.filter(v => !v.verified).length}\n\n`;

    const sortedVaccinations = [...vaccinations].sort(
      (a, b) => parseLocalDate(b.date).getTime() - parseLocalDate(a.date).getTime()
    );

    sortedVaccinations.forEach((vax, index) => {
      summary += `${index + 1}. ${vax.vaccineName} - Dose ${vax.doseNumber}\n`;
      summary += `   Date: ${formatDate(vax.date)}\n`;
      summary += `   Country: ${vax.countryGiven}\n`;
      summary += `   Location: ${vax.location}\n`;
      summary += `   Provider: ${vax.provider}\n`;
      summary += `   Status: ${vax.verified ? 'Verified ✓' : 'Pending Review'}\n`;
      if (vax.notes) {
        summary += `   Notes: ${vax.notes}\n`;
      }
      summary += '\n';
    });

    summary += '═══════════════════════════════════════\n';
    summary += `Generated: ${new Date().toLocaleString()}\n`;
    summary += 'DOZEY - dozeyrecords.com\n';
    summary += '═══════════════════════════════════════\n';

    const blob = new Blob([summary], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'vaccination-records.txt';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleSendEmail = () => {
    alert(`Email would be sent to: ${email}\n\nIn a production app, this would send a secure link to the recipient.`);
    setEmail('');
    setMessage('');
  };

  return (
    <div>
      <div className="bg-white rounded-2xl border-0 p-8">
        <div className="flex items-center gap-3 mb-6">
          <Share2 className="w-8 h-8 text-[#1d1d1f]/30" />
          <div>
            <h1 className="text-[#1d1d1f] font-semibold">Share Records</h1>
            <p className="text-[#86868b]">Securely share your vaccination records with healthcare providers</p>
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-4 gap-4 mb-8">
          <button
            onClick={() => setShareMethod('card')}
            className={`p-6 rounded-2xl border transition-all ${
              shareMethod === 'card'
                ? 'border-[#4a7fb5] bg-[#4a7fb5]/5'
                : 'border-black/5 hover:border-[#4a7fb5]/50'
            }`}
          >
            <CreditCard className={`w-8 h-8 mx-auto mb-3 ${shareMethod === 'card' ? 'text-[#4a7fb5]' : 'text-[#1d1d1f]/30'}`} />
            <h3 className="text-[#1d1d1f] font-semibold mb-1">Vaccine Card</h3>
            <p className="text-[#86868b] text-sm">COVID-19 style card format</p>
          </button>

          <button
            onClick={() => setShareMethod('link')}
            className={`p-6 rounded-2xl border transition-all ${
              shareMethod === 'link'
                ? 'border-[#4a7fb5] bg-[#4a7fb5]/5'
                : 'border-black/5 hover:border-[#4a7fb5]/50'
            }`}
          >
            <LinkIcon className={`w-8 h-8 mx-auto mb-3 ${shareMethod === 'link' ? 'text-[#4a7fb5]' : 'text-[#1d1d1f]/30'}`} />
            <h3 className="text-[#1d1d1f] font-semibold mb-1">Share Link</h3>
            <p className="text-[#86868b] text-sm">Generate a secure link</p>
          </button>

          <button
            onClick={() => setShareMethod('email')}
            className={`p-6 rounded-2xl border transition-all ${
              shareMethod === 'email'
                ? 'border-[#4a7fb5] bg-[#4a7fb5]/5'
                : 'border-black/5 hover:border-[#4a7fb5]/50'
            }`}
          >
            <Mail className={`w-8 h-8 mx-auto mb-3 ${shareMethod === 'email' ? 'text-[#4a7fb5]' : 'text-[#1d1d1f]/30'}`} />
            <h3 className="text-[#1d1d1f] font-semibold mb-1">Send Email</h3>
            <p className="text-[#86868b] text-sm">Email directly to provider</p>
          </button>

          <button
            onClick={() => setShareMethod('pdf')}
            className={`p-6 rounded-2xl border transition-all ${
              shareMethod === 'pdf'
                ? 'border-[#4a7fb5] bg-[#4a7fb5]/5'
                : 'border-black/5 hover:border-[#4a7fb5]/50'
            }`}
          >
            <Download className={`w-8 h-8 mx-auto mb-3 ${shareMethod === 'pdf' ? 'text-[#4a7fb5]' : 'text-[#1d1d1f]/30'}`} />
            <h3 className="text-[#1d1d1f] font-semibold mb-1">Full Summary</h3>
            <p className="text-[#86868b] text-sm">Download detailed summary</p>
          </button>
        </div>

        {shareMethod === 'card' && (
          <div className="bg-[#f5f5f7] p-6 rounded-2xl">
            <h3 className="text-[#1d1d1f] font-semibold mb-4">Vaccine Card Export</h3>
            <p className="text-[#86868b] mb-6 text-sm">
              Download your vaccination records in a compact card format similar to COVID-19 vaccine cards.
              Lists each vaccine with dose numbers, dates, providers, and locations.
            </p>

            <div className="bg-white border-2 border-[#4a7fb5] rounded-xl p-6 mb-6 max-w-md mx-auto shadow-sm">
              <div className="text-center border-b-2 border-[#4a7fb5] pb-3 mb-4">
                <div className="text-[#4a7fb5] font-semibold text-lg">VACCINATION RECORD CARD</div>
                <div className="text-[#8aab45] font-semibold text-sm">DOZEY</div>
              </div>
              <div className="space-y-2 text-sm mb-4">
                <div className="flex">
                  <span className="text-[#86868b] w-28 shrink-0">Name:</span>
                  <span className="text-[#1d1d1f] font-medium">{profile?.fullName || 'Your Name'}</span>
                </div>
                <div className="flex">
                  <span className="text-[#86868b] w-28 shrink-0">Date of Birth:</span>
                  <span className="text-[#1d1d1f] font-medium">{formatDate(profile?.dateOfBirth)}</span>
                </div>
              </div>
              <div className="border-t border-0 pt-3">
                <div className="text-xs text-[#86868b] mb-2 uppercase tracking-wide font-medium">Vaccinations ({vaccinations.length})</div>
                {vaccinations.slice(0, 3).map((v, i) => (
                  <div key={i} className="flex justify-between text-xs py-1 border-b border-black/5">
                    <span className="font-medium text-[#1d1d1f]">{v.vaccineName} (Dose {v.doseNumber})</span>
                    <span className="text-[#86868b]">{formatDate(v.date, { month: 'short', day: 'numeric', year: '2-digit' })}</span>
                  </div>
                ))}
                {vaccinations.length > 3 && (
                  <div className="text-xs text-[#86868b] pt-1">+ {vaccinations.length - 3} more</div>
                )}
              </div>
            </div>

            <button
              onClick={generateVaccineCard}
              className="w-full bg-[#4a7fb5] hover:bg-[#3a6a9a] text-white py-3 rounded-full transition-colors flex items-center justify-center gap-2 font-semibold"
            >
              <CreditCard className="w-5 h-5" />
              Download Vaccine Card
            </button>
          </div>
        )}

        {shareMethod === 'link' && (
          <div className="bg-[#f5f5f7] p-6 rounded-2xl">
            <h3 className="text-[#1d1d1f] font-semibold mb-4">Generate Secure Link</h3>
            
            <div className="space-y-4 mb-6">
              <CustomSelect
                id="expiration"
                label="Link Expiration"
                value={String(expirationDays)}
                onChange={(val) => setExpirationDays(parseInt(val))}
                options={[
                  { value: '1', label: '1 day' },
                  { value: '7', label: '7 days' },
                  { value: '30', label: '30 days' },
                  { value: '90', label: '90 days' },
                ]}
              />

              <div className="flex items-center gap-2">
                <input
                  type="checkbox"
                  id="allowDownload"
                  checked={allowDownload}
                  onChange={(e) => setAllowDownload(e.target.checked)}
                  className="w-4 h-4 text-[#8aab45]"
                />
                <label htmlFor="allowDownload" className="text-[#1d1d1f]">
                  Allow recipient to download records
                </label>
              </div>
            </div>

            <div className="bg-white p-4 rounded-2xl border-0 flex items-center gap-3 mb-4">
              <code className="flex-1 text-sm text-[#86868b] break-all">{mockShareLink}</code>
              <button
                onClick={handleCopyLink}
                className="bg-[#8aab45] hover:bg-[#6d8a35] text-white px-4 py-2 rounded-full transition-colors flex items-center gap-2"
              >
                {copied ? (
                  <>
                    <CheckCircle className="w-4 h-4" />
                    Copied!
                  </>
                ) : (
                  <>
                    <Copy className="w-4 h-4" />
                    Copy
                  </>
                )}
              </button>
            </div>

            <p className="text-[#86868b] text-sm">
              This link will expire in {expirationDays} day{expirationDays !== 1 ? 's' : ''} and can be accessed by anyone with the URL.
            </p>
          </div>
        )}

        {shareMethod === 'email' && (
          <div className="bg-[#f5f5f7] p-6 rounded-2xl">
            <h3 className="text-[#1d1d1f] font-semibold mb-4">Send via Email</h3>
            
            <div className="space-y-4">
              <div>
                <label htmlFor="recipientEmail" className="block text-[#1d1d1f] mb-2">
                  Recipient Email *
                </label>
                <input
                  type="email"
                  id="recipientEmail"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  placeholder="doctor@clinic.com"
                  className="w-full px-4 py-2 bg-[#f5f5f7] border-0 rounded-xl focus:ring-2 focus:ring-[#4a7fb5] focus:border-transparent outline-none"
                />
              </div>

              <div>
                <label htmlFor="emailMessage" className="block text-[#1d1d1f] mb-2">
                  Message (Optional)
                </label>
                <textarea
                  id="emailMessage"
                  value={message}
                  onChange={(e) => setMessage(e.target.value)}
                  rows={4}
                  placeholder="Add a message to your healthcare provider..."
                  className="w-full px-4 py-2 bg-[#f5f5f7] border-0 rounded-xl focus:ring-2 focus:ring-[#4a7fb5] focus:border-transparent outline-none resize-none"
                />
              </div>

              <button
                onClick={handleSendEmail}
                disabled={!email}
                className="w-full bg-[#8aab45] hover:bg-[#6d8a35] disabled:bg-[#f5f5f7] disabled:text-[#86868b] disabled:cursor-not-allowed text-white py-3 rounded-full transition-colors flex items-center justify-center gap-2"
              >
                <Mail className="w-5 h-5" />
                Send Email
              </button>
            </div>
          </div>
        )}

        {shareMethod === 'pdf' && (
          <div className="bg-[#f5f5f7] p-6 rounded-2xl">
            <h3 className="text-[#1d1d1f] font-semibold mb-4">Download Full Summary</h3>
            
            <div className="bg-white p-6 rounded-2xl border-0 mb-4">
              <h4 className="text-[#1d1d1f] font-semibold mb-3">What's included:</h4>
              <ul className="space-y-2 text-[#86868b]">
                <li className="flex items-center gap-2">
                  <CheckCircle className="w-5 h-5 text-green-500" />
                  Complete patient profile
                </li>
                <li className="flex items-center gap-2">
                  <CheckCircle className="w-5 h-5 text-green-500" />
                  Full vaccination history ({vaccinations.length} records)
                </li>
                <li className="flex items-center gap-2">
                  <CheckCircle className="w-5 h-5 text-green-500" />
                  Country residence timeline
                </li>
                <li className="flex items-center gap-2">
                  <CheckCircle className="w-5 h-5 text-green-500" />
                  Verification status for each vaccine
                </li>
              </ul>
            </div>

            <button
              onClick={generatePDF}
              className="w-full bg-[#8aab45] hover:bg-[#6d8a35] text-white py-3 rounded-full transition-colors flex items-center justify-center gap-2"
            >
              <Download className="w-5 h-5" />
              Download Summary (TXT)
            </button>
            
            <p className="text-[#86868b] text-sm mt-4">
              Note: In a production version, this would generate a professionally formatted PDF document.
            </p>
          </div>
        )}

        <div className="mt-8 bg-[#f5f5f7] rounded-2xl border-0 p-5">
          <div className="flex items-center gap-2 mb-2">
            <Shield className="w-5 h-5 text-[#1d1d1f]/30" />
            <h4 className="text-[#1d1d1f] font-semibold">Privacy & Security</h4>
          </div>
          <ul className="text-[#86868b] text-sm space-y-1">
            <li>All shared links are encrypted and expire automatically</li>
            <li>You can revoke access at any time from your dashboard</li>
            <li>Recipients cannot modify your records</li>
            <li>You'll be notified when someone accesses your records</li>
          </ul>
        </div>
      </div>
    </div>
  );
}
